In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("/content/twcs.csv",encoding='latin-1')

In [3]:
data.shape

(1048575, 7)

In [4]:
data.head(4)

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   

                                                text response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2   
1      @sprintcare and how do you propose we do that               NaN   
2  @sprintcare I have sent several private messag...                 1   
3  @115712 Please send us a Private Message so th...                 3   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0

In [5]:
data['text'][1]

'@sprintcare and how do you propose we do that'

In [ ]:
#Lowercasing

In [6]:
data["text"]=data["text"].str.lower()

In [7]:
data['text'][3]

'@115712 please send us a private message so that we can further assist you. just click â\x80\x98messageâ\x80\x99 at the top of your profile.'

In [8]:
import re

In [9]:
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub("",text)

In [10]:
data["text"]=data["text"].apply(remove_html_tags)

In [11]:
data["text"].head(4)

0    @115712 i understand. i would like to assist y...
1        @sprintcare and how do you propose we do that
2    @sprintcare i have sent several private messag...
3    @115712 please send us a private message so th...
Name: text, dtype: object

In [ ]:
# To remove URL

In [12]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub("",text)

In [13]:
data["text"]=data["text"].apply(remove_url)

In [14]:
data["text"].head(10)

0    @115712 i understand. i would like to assist y...
1        @sprintcare and how do you propose we do that
2    @sprintcare i have sent several private messag...
3    @115712 please send us a private message so th...
4                                   @sprintcare i did.
5    @115712 can you please send us a private messa...
6            @sprintcare is the worst customer service
7    @115713 this is saddening to hear. please shoo...
8    @sprintcare you gonna magically change your co...
9    @115713 we understand your concerns and we'd l...
Name: text, dtype: object

In [15]:
import string

In [16]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
exclude=string.punctuation

In [18]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,"")
    return text

In [19]:
text="string @ *() with punctuaion.!"

In [20]:
remove_punc(text)

'string   with punctuaion'

In [21]:
data["text"]=data["text"].apply(remove_punc)

In [22]:
data["text"]

0          115712 i understand i would like to assist you...
1               sprintcare and how do you propose we do that
2          sprintcare i have sent several private message...
3          115712 please send us a private message so tha...
4                                           sprintcare i did
                                 ...                        
1048570                   when morrisons does you good 🙌 
1048571    393038  along with your more card and address ...
1048572                                          morrisons  
1048573    morrisons watford bought crayfish tails the ot...
1048574    393038 hi adam im really sorry about this can ...
Name: text, Length: 1048575, dtype: object

In [ ]:
##Process Slang words

In [23]:
chat_words={
    "AFAIK":"As Far As I Know",
"AFK":"Away From Keyboard",
"ASAP":"As Soon As Possible",
"ATK":"At The Keyboard",
"ATM":"At The Moment",
"A3":"Anytime, Anywhere, Anyplace",
"BAK":"Back At Keyboard",
"BBL":"Be Back Later",
"BBS":"Be Back Soon",
"BFN":"Bye For Now",
"B4N":"Bye For Now",
"BRB":"Be Right Back",
"BRT":"Be Right There",
"BTW":"By The Way",
"B4":"Before",
"B4N":"Bye For Now",
"CU":"See You",
"CUL8R":"See You Later",
"CYA":"See You",
"FAQ":"Frequently Asked Questions",
"FC":"Fingers Crossed",
"FWIW":"For What It's Worth",
"FYI":"For Your Information",
"GAL":"Get A Life",
"GG":"Good Game",
"GN":"Good Night",
"GMTA":"Great Minds Think Alike",
"GR8":"Great!",
"G9":"Genius",
"IC":"I See",
"ICQ":"I Seek you (also a chat program",
"ILU":"I Love You",
"IMHO":"In My Honest/Humble Opinion",
"IMO":"In My Opinion",
"IOW":"In Other Words",
"IRL":"In Real Life",
"KISS":"Keep It Simple, Stupid",
"LDR":"Long Distance Relationship",
"LMAO":"Laugh My A.. Off",
"LOL":"Laughing Out Loud",
"LTNS":"Long Time No See",
"L8R":"Later",
"MTE":"My Thoughts Exactly",
"M8":"Mate",
"NRN":"No Reply Necessary",
"OIC":"Oh I See",
"PITA":"Pain In The A..",
"PRT":"Party",
"PRW":"Parents Are Watching",
"QPSA":"Que Pasa?",
"ROFL":"Rolling On The Floor Laughing",
"ROFLOL":"Rolling On The Floor Laughing Out Loud",
"ROTFLMAO":"Rolling On The Floor Laughing My A.. Off",
"SK8":"Skate",
"STATS":"Your sex and age",
"ASL":"Age, Sex, Location",
"THX":"Thank You",
"TTFN":"Ta-Ta For Now!",
"TTYL":"Talk To You Later",
"U":"You",
"U2":"You Too",
"U4E":"Yours For Ever",
"WB":"Welcome Back",
"WTF":"What The F...",
"WTG":"Way To Go!",
"WUF":"Where Are You From?",
"W8":"Wait...",
"7K":"Sick:-D Laugher",
"TFW":"That feeling when. TFW internet slang often goes in a caption to an image.",
"MFW":"My face when",
"MRW":"My reaction when",
"IFYP":"I feel your pain",
"LOL":"Laughing out loud",
"TNTL":"Trying not to laugh",
"JK":"Just kidding",
"IDC":"I don’t care",
"ILY":"I love you",
"IMU":"I miss you",
"ADIH":"Another day in hell",
"IDC":"I don’t care",
"ZZZ":"Sleeping, bored, tired",
"WYWH":"Wish you were here",
"TIME":"Tears in my eyes",
"BAE":"Before anyone else",
"FIMH":"Forever in my heart",
"BSAAW":"Big smile and a wink",
"BWL":"Bursting with laughter",
"LMAO":"Laughing my a** off",
"BFF":"Best friends forever",
"CSL":"Can’t stop laughing"
}

In [24]:
chat_words["LMAO"]

'Laughing my a** off'

In [25]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [26]:
text="FYI this is not true"
text2="LAMO the class was so funny"
text3="i want report ASAP"

In [27]:
chat_conversion(text)

'For Your Information this is not true'

In [28]:
chat_conversion(text3)

'i want report As Soon As Possible'

In [29]:
data["text"]=data["text"].apply(chat_conversion)

In [30]:
data["text"].sample(10)

665718     xboxsupport hi i used a code to have xbox live...
513706     amazonhelp 115830 you quite literally have the...
971659     shoutout to 115817 for losing me over 150 wort...
704279     amazonhelp sure heres the item â£137949 in the...
515654     airtelcare do You ve an outlet in ikotun lagos...
425639     askamex why does your so require wifi to authe...
420610     228951 i am showing that the package was deliv...
900656     americanair how in the world would they expect...
1043663    thisthis is why you don’t fly with americana...
255128     126503 please contact our bluebird customer se...
Name: text, dtype: object

In [ ]:
# spell correction

In [31]:
text1="this is my processing notebook pleae download this ntebook"

In [32]:
import textblob

In [33]:
from textblob import TextBlob

In [34]:
txtblob=TextBlob(text)

In [35]:
txtblob.correct().string

'FYI this is not true'

In [36]:
def correct_column(data, text):

        # Iterate over each entry in the specified column
    for index, row in data.iterrows():
        # Get the text from the specified column
        text = row[text]

        # Create a TextBlob object
        blob = TextBlob(text)

        # Correct the text
        corrected_text = str(blob.correct())

        # Update the DataFrame with the corrected text
        data.at[index, text] = corrected_text

    return data



In [ ]:
# stop word removing

In [37]:
import nltk

In [38]:
from nltk.corpus import stopwords

In [39]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [40]:
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [41]:
def remove_stopwords(text):
    new_text=[]

    for word in text.split():
        if word in stopwords.words("english"):
            new_text.append("")
        else:
            new_text.append(word.strip())


    return " ".join(new_text).replace("   ","")

In [42]:
text="i am sunny and we are learning nlp and here is why nlp are important"

In [43]:
remove_stopwords(text)

'  sunny learning nlp  nlp  important'

In [44]:
def remove_stopwords(text):

  new_text=[]
  for word in text.split():
    if word not in Stopword:
      new_text.append(word)
  return " ".join(new_text)

In [45]:
pip install emoji


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.5/421.5 kB 7.5 MB/s eta 0:00:00


In [46]:
import emoji

In [47]:
original_text = "Hello,😊 how are you today? 🌟"

In [48]:
def remove_emoji(text):
    clean_text=emoji.demojize(text)
    return clean_text

In [49]:
remove_emoji(original_text)

'Hello,:smiling_face_with_smiling_eyes: how are you today? :glowing_star:'

In [50]:
import re
def remove_emojis_manually(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F700-\U0001F77F"  # alchemical symbols
                               u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                               u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                               u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                               u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                               u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                               u"\U00002702-\U000027B0"  # Dingbats
                               u"\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)
    clean_text = emoji_pattern.sub(r'', text)
    return clean_text

In [51]:
pip install spacy

In [54]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [55]:
from nltk.stem import WordNetLemmatizer

In [56]:
def lammatization(text):
    words=text.split()
    lemmetizer=WordNetLemmatizer()
    lemetized_word=[lemmetizer.lemmatize(word) for word in words]
    return lemetized_word

In [57]:
data["text"]=data["text"].apply(lammatization)

In [58]:
import pandas as pd

In [69]:
data=pd.DataFrame({"text":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,1,0,0]})

In [70]:
pip install scikit-learn

In [71]:
from sklearn.feature_extraction.text import CountVectorizer

In [72]:
BOW=CountVectorizer()

In [73]:
document_matrix=BOW.fit_transform(data["text"])

In [74]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [75]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [76]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]])

In [77]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]])

In [78]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]])

In [79]:
document_matrix[3].toarray()

array([[1, 1, 0, 0, 1]])

In [80]:
bigram=CountVectorizer(ngram_range=(2,2))

In [81]:
bigramvocab=bigram.fit_transform(data["text"])

In [82]:
bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [83]:
trigram=CountVectorizer(ngram_range=(3,3))

In [84]:
trigramdata=trigram.fit_transform(data["text"])

In [85]:
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [86]:
mix=CountVectorizer(ngram_range=(1,2))

In [87]:
mix_vocab=mix.fit_transform(data["text"])

In [88]:
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [90]:
tfidf=TfidfVectorizer()

In [91]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [92]:
tfidf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [93]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])